---
- hosts: localhost  # target localhost since using ansible-pull
  connection: local # do not default to ssh
  become: true      # enable sudo

  tasks:
  - name: install packages
    package:
      name:
        - gh
        - docker

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/hojelse/.bashrc
      owner: hojelse
      group: hojelse
