- name: Download discord
  get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: "{{ ansible_env.HOME }}/Downloads/discord.deb"

- name: Install discord
  apt:
    deb: "{{ ansible_env.HOME }}/Downloads/discord.deb"
