- name: Add virtualbox Apt signing key
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Add virtualbox repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian jammy contrib
    state: present

- name: Add vagrant Apt signing key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add vagrant repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com jammy main
    state: present

- name: Add packages
  apt:
    name:
      - vagrant
      - virtualbox