- name: download nvm install script
  get_url:
    url:  https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
    dest: /home/hojelse/Downloads/nvm-install.sh
    mode: 0777

- name: install nvm
  shell: /home/hojelse/Downloads/nvm-install.sh
  args:
    creates: "/home/hojelse/.nvm/nvm.sh"

- name: Install node and set version
  become: yes
  become_user: root
  shell: "source /root/.nvm/nvm.sh && nvm install 18" 
  args:
    executable: /bin/bash
